### ISSUE TITLE
Batch VAAs

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/wormhole#1679]
# Batch VAAs

## Overview

As an integrator who composes multiple Wormhole-using contracts, I want to receive an attestation which contains all of the messages emitted in a transaction. Messages could opt-out of a batch by setting a nonce of `0`.

## Current Behavior

The only way to compose multiple messages is to submit separate VAAs to the target contract in the same call. Each of these messages would need to be verified separately, adding prohibitive costs. This is also inconvenient to query for / collect from the guardians.

### Guardian

All messages will continue to produce a "payload 1" VAA. The guardian will collect messages with a non-zero nonce within the same transaction and produce a Batch VAA (payload 2).

### Smart Contract

(These notes are very EVM implementation specific.)

The Wormhole core contract will parse the Batch VAA into a new struct (VM2) and compute the batch hash which is the hash-of-hashes of each observation. The core contract will then verify the signatures against the batch hash. The calling contract may decide if they want to cache the hashes in the core contract state, which will allow for cheaper verification of individual messages in the batch later in the transaction.

The Headless VAAs within the batch will be parsed into the existing VM struct (version 3) while leaving the signatures and guardian set `null`. To verify these Headless VAAs the hash must be cached by the Wormhole core contract during batch signature verification.

The contract that verified the batch can clear the cached Headless VAA hashes from the core contract state after processing. This should be done atomically to reduce the gas costs.

### Finer Grain Batches

I may want to create multiple groups of these messages within the same transaction, which can be controlled by setting the nonce field.

### Partial Batches

Allow the redeemer to submit partial batches by adding an index-Headless VAA pair which will allow the core contract to verify each observation's hash against the array of hashes in the batch. The purpose of this is to further reduce gas usage, e.g. if not all messages in a batch are relevant to every chain being relayed to. The structure of the batch signed by the guardian would remain the same - this is solely a off-chain relayer function.

## Tracker

- [x] EVM Core Contracts to parse and verify Batch VAAs and Headless VAAs, update interfaces
- [x] #1857
- [x] #1893
- [x] #1891
- [ ] SDK parsing functions
- [ ] Book section with examples
