### ISSUE TITLE
Tracking issue for Sui integration - SDK, Token bridge relayer, tooling, rollout

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2354]
This issue is for grouping tooling and rollout related tasks necessary for integrating Sui into the Wormhole network.

Other tracking issues:

- https://github.com/wormhole-foundation/wormhole/issues/1944
- https://github.com/wormhole-foundation/wormhole/issues/2353
- https://github.com/wormhole-foundation/wormhole/issues/2443

Tasks:

- [x] #2046
- [x] #1946
- [x] #1980
- [x] #2044
- [x] #1964
- [ ] #2363
- [x] #2356
- [x] #2419
- [x] #2446
- [x] #2448
- [x] #2449
- [x] #2450
- [x] https://github.com/wormhole-foundation/example-token-bridge-relayer/issues/23
- [x] https://github.com/wormhole-foundation/example-token-bridge-relayer/issues/16
- [x] https://github.com/wormhole-foundation/example-token-bridge-relayer/issues/17
- [x] https://github.com/wormhole-foundation/example-token-bridge-relayer/issues/19
- [x] https://github.com/wormhole-foundation/example-token-bridge-relayer/issues/27
- [x] #2489
- [x] #2490
- [x] #2562
- [x] #2554
- [x] #2555
- [x] #2556
- [x] #2563
- [x] #2595
- [x] #2597
- [x] #2670

**Comment by evan-gray** [comment]
Sui has been live for a while now.
