### ISSUE TITLE
Tracking issue for Base integration - Portalbridge, Dashboard, Monitor, Explorer

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2436]
This issue is for grouping Base integration related tasks that are outside of this repo.

### Task list

- [x] https://github.com/wormhole-foundation/wormhole-dashboard/issues/53
- [x] https://github.com/wormhole-foundation/wormhole-dashboard/issues/65
- [ ] https://github.com/wormhole-foundation/wormhole-web/issues/86
- [x] Add Base mainnet support to Portalbridge UI
