### ISSUE TITLE
Tracking issue for Sui integration - Portalbridge, WH scaffolding, WH Monitor, WH Dashboard, Explorer

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2443]
This issue is for grouping the sui integration related misc tasks that are not strictly necessary for rollout.

### Other tracking issues for the same project:

- https://github.com/wormhole-foundation/wormhole/issues/2353
- https://github.com/wormhole-foundation/wormhole/issues/2354
- https://github.com/wormhole-foundation/wormhole/issues/1944

### Task list

- [ ] https://github.com/wormhole-foundation/wormhole-scaffolding/issues/41
- [x] https://github.com/wormhole-foundation/wormhole-dashboard/issues/74
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/55

### Additional todos

- [x] Add Sui to wormhole dashboard
- [ ] Update Explorer to support Sui transactions
