### ISSUE TITLE
Tracking issue for Generic relayers -  SDK, Example application (tutorial), Template

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2633]
This issue is for grouping SDK and related tasks. More specifically:

- FInalize the SDK
- Create an example application (with a tutorial)
- Create a scaffolding template

### Other tracking issues for the same project:

- https://github.com/wormhole-foundation/wormhole/issues/2651
- https://github.com/wormhole-foundation/wormhole/issues/2650
- https://github.com/wormhole-foundation/wormhole/issues/2638
- https://github.com/wormhole-foundation/wormhole/issues/2635
- https://github.com/wormhole-foundation/wormhole/issues/2634

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2681
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2682
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2683
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2684
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2685
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2686
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2688
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2690
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2700
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2873
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2874
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2875
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2930
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2977
```
