### ISSUE TITLE
Tracking issue for Generic relayers - Forge tests, Tilt / CI pipeline

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2634]
This issue is for grouping forge test and CI pipeline / Tilt related tasks.

### Other tracking issues for the same project:

- https://github.com/wormhole-foundation/wormhole/issues/2651
- https://github.com/wormhole-foundation/wormhole/issues/2650
- https://github.com/wormhole-foundation/wormhole/issues/2638
- https://github.com/wormhole-foundation/wormhole/issues/2635
- https://github.com/wormhole-foundation/wormhole/issues/2633

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2655
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2687
- [x] https://github.com/wormhole-foundation/wormhole/issues/2657
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2689
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2661
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2691
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2701
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2703
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2702
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2699
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2704
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2692
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2693
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2705
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2706
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2707
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2719
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2694
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2716
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2727
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2728
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2695
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2725
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2724
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2723
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2696
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2722
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2721
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2720
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2715
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2697
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2714
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2730
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2731
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2732
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2751
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2755
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2760
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2748
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2744
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2698
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2781
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2783
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2726
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2729
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2938
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2939
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2947
```
