### ISSUE TITLE
Tracking issue for Generic relayers - Mainnet rollout & governance 

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2635]
This issue is for grouping tasks that are necessary for rolling out generic relayers. More specifically:

- npm package release
- publishing documentation
- creating demo projects
- other administrative and misc tasks (such as setting configs or other finishing touches)

### Other tracking issues for the same project:

- https://github.com/wormhole-foundation/wormhole/issues/2651
- https://github.com/wormhole-foundation/wormhole/issues/2650
- https://github.com/wormhole-foundation/wormhole/issues/2638
- https://github.com/wormhole-foundation/wormhole/issues/2634
- https://github.com/wormhole-foundation/wormhole/issues/2633

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2654
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2718
- [ ] Get documentation + demo projects published
- [ ] Get an integrator to integrate successfully with minimal help (?)
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2758
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2776
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2778
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2872
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2985
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3163
```
