### ISSUE TITLE
Tracking issue for Generic relayers - Documentation

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2638]
This issue is for grouping documentation tasks in connection to generic relayers. More specifically:

- Writing up docs
- Extending the codebase with comments

### Other tracking issues for the same project:

- https://github.com/wormhole-foundation/wormhole/issues/2651
- https://github.com/wormhole-foundation/wormhole/issues/2650
- https://github.com/wormhole-foundation/wormhole/issues/2635
- https://github.com/wormhole-foundation/wormhole/issues/2634
- https://github.com/wormhole-foundation/wormhole/issues/2633

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2677
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2678
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2679
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2680
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2876
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3012
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3013
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3015
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3090
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3092
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3141
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3142
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3143
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3144
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3145
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3191
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3192
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3193
```
