### ISSUE TITLE
Tracking issue for Generic relayers - Offchain components and service reliability

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2650]
This issue is for grouping tasks to implement offchain infrastructure for generic relayers. Such as:

- Kubernetes deployment files
- Logging, metrics, alerts and their visibility
- Status API
- Integrating wallet rebalancing from the relayer engine
- Stability improvements

### Other tracking issues for the same project:

- https://github.com/wormhole-foundation/wormhole/issues/2651
- https://github.com/wormhole-foundation/wormhole/issues/2638
- https://github.com/wormhole-foundation/wormhole/issues/2635
- https://github.com/wormhole-foundation/wormhole/issues/2634
- https://github.com/wormhole-foundation/wormhole/issues/2633

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2662
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2665
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2671
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2672
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2673
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2676
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2774
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2775
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2871
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2941
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2942
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2943
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2944
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2945
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3014
```
