### ISSUE TITLE
Tracking issue for Generic relayers - Misc tasks

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole#2651]
This issue is for grouping misc or ad-hoc tasks in connection to generic relayers. Such as:

- Contract changes/improvements
- Adding new integration tests
- Any task which doesn't fit into the other tracking issues

### Other tracking issues for the same project:

- https://github.com/wormhole-foundation/wormhole/issues/2650
- https://github.com/wormhole-foundation/wormhole/issues/2638
- https://github.com/wormhole-foundation/wormhole/issues/2635
- https://github.com/wormhole-foundation/wormhole/issues/2634
- https://github.com/wormhole-foundation/wormhole/issues/2633

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2708
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2741
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2825
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2894
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2928
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2929
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2940
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2955
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2973
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2974
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2975
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2976
- [ ] https://github.com/wormhole-foundation/wormhole/issues/2978
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3053
```
