### ISSUE TITLE
Tracking issue for *ADD_PROJECT* - *ADD_COMPONENT*

### ISSUE THREAD

**Issue by gabrielt2r** [wormhole-foundation/wormhole#3616]
[This](url) issue is for grouping *ADD_COMPONENT* related tasks that are necessary for *ADD_PROJECT*.

### Other tracking issues for the same project:

- #XXXX
- #XXXX
- #XXXX

```[tasklist]
### Task list
- [x] XXXX
- [x] XXXX
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3602
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3611
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3613
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3614
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3615
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3500
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3612
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3538
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3610
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3606
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3606
```
```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3602
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3602
```

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3602
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3611
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3611
```

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3614
- [ ] https://github.com/wormhole-foundation/wormhole/issues/3613
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3538
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3602
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3611
- [ ] https://github.com/wormhole-foundation/wormhole/pull/3611
```
